# Generated by Django 3.0.2 on 2020-01-17 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_auto_20200117_0720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='image_height',
        ),
        migrations.RemoveField(
            model_name='news',
            name='image_width',
        ),
        migrations.AddField(
            model_name='comments',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, max_length=200, upload_to='news_images/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
