# Generated by Django 3.0.2 on 2020-01-09 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_auto_20200109_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, height_field='100', upload_to='news_images/%Y/%m/%d', width_field='100'),
        ),
    ]
