# Generated by Django 3.0.2 on 2020-01-09 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_auto_20200109_0617'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image_height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='news',
            name='image_width',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, height_field='image_height', upload_to='news_images/%Y/%m/%d', width_field='image_width'),
        ),
    ]
