# Generated by Django 3.0.2 on 2020-01-17 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_auto_20200117_0903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='post',
            new_name='news',
        ),
    ]
