# Generated by Django 3.0.2 on 2020-01-09 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_auto_20200109_0623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='image_height',
        ),
        migrations.RemoveField(
            model_name='news',
            name='image_width',
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, max_length=500, upload_to='news_images/%Y/%m/%d'),
        ),
    ]
