# Generated by Django 3.0.2 on 2020-01-09 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0007_auto_20200109_0625'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image_height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='news',
            name='image_width',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, height_field=models.IntegerField(default=0), max_length=500, upload_to='news_images/%Y/%m/%d', width_field=models.IntegerField(default=0)),
        ),
    ]
