# Generated by Django 3.0.2 on 2020-01-09 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0008_auto_20200109_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, height_field='image_height', max_length=200, upload_to='news_images/%Y/%m/%d', width_field=models.IntegerField(default=0)),
        ),
    ]
